### ISSUE TITLE
Mailbox swipe option and open

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#108]
**Is your feature request related to a problem? Please describe.**

Speed up sorting out messages and opening messages

 

**Describe the solution you'd like**

Like you can swipe away notifications individually you can delete emails by swiping them individually

Tapping message opens default email app

**Comment by zobnin** [comment]
1. A very bad idea. You could accidentally swipe and delete an important email.
2. Technically impossible.

**Comment by zobnin** [comment]
1. No. First of all Gmail uses swipe to archive by default. Second: it's much harder to accidentally swipe an email in a mail app than on a desktop, where an email can easily be mistaken for a regular notification, not to mention that the desktop is visible on the screen for a much longer time.
2. The bottom button doesn't open the email view, nor just the mail client. It opens a window for composing a new email. I don't think you want this window to open instead of the preview.

**Comment by Lorestan00** [comment]
1. Fair enough but it can be changed to delete. Either way quick way to triage emails. Like I said I get your on accidental deleted on home screens so suggested long swipe..perhaps not possible. My point is a quick way to deleting emails from the home screen without having to leave it

2. My fault I meant the reply bottom button opens email app. I really just want html view rather than the basic preview. Like the one get when you add open as a bottom button which gives you html preview.

**Comment by zobnin** [comment]
1. Long press -> Delete
2. Long press -> Open

**Comment by Lorestan00** [comment]
Cool. I'll try that
