### ISSUE TITLE
Android widget marging

### ISSUE THREAD

**Issue by Peaulixs** [zobnin/aio#117]
With the card theme why android widgets are centered but AIO widgets are more towards the top.  When you have several AOI widgets and several Android widgets it gives a weird appearance considering that the spacing is not the same everywhere

![Screenshot_20240518-153244.png](https://github.com/zobnin/aio/assets/62362754/27f83af7-d74d-486f-99a8-f05db3177ecb)

![Screenshot_20240518-153219.png](https://github.com/zobnin/aio/assets/62362754/05c7253e-ab18-4715-bf8c-c68b2f45c1cb)

**Comment by zobnin** [comment]
The indents in AIO widgets vary because they are designed to be used in different themes, most of which have headers and no borders of the same size.

At the same time, Android widgets can have completely different indents and sizes. In your example, the widget is "correct" with proper indents on all sides, but this is not always the case.

In other words, this is a combination of factors inherent to both AIO and Android and its widgets. I probably won't be able to fix it without breaking compatibility with different themes along the way.
