### ISSUE TITLE
Pocketcast no longer shows the podcast icon

### ISSUE THREAD

**Issue by brunosabin** [zobnin/aio#118]
**Describe the bug**
For the past few months, the cover art of current playing podcast in pocketcast no longer shows. 

**To Reproduce**
1. Enable AIO "player" widget
2. Go to Pocketcast and start playing any podcast with a cover artwork
3. Go back to AIO while the podcast is running in the background 
4. Notice the icon on the left of the player widget remains default blank 

**Expected behavior**
The I on used to show correctly in AIO a few months ago (I held back reporting hoping it was temporary glitch). Using Samsung default OneUI launcher never stopped working hence reporting here. 

**Screenshots**
![image](https://github.com/zobnin/aio/assets/8375970/38c4089e-06f7-4ba3-bda2-68c2ab093cf6)

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - Android version: Android 14
 - AIO Version: 5.2.4

**Additional context**
N/A

**Comment by zobnin** [comment]
No launcher problem.All AIO Launcher does is display the cover art that the application publishes using a special API. Therefore, if the cover art is missing, it's an issue with the application. Meanwhile, Android itself may continue to show the cover art correctly because it uses a slightly different method to obtain it.
