### ISSUE TITLE
Opening websites directly from search bar

### ISSUE THREAD

**Issue by ChibyX** [zobnin/aio#127]
Currently if I type web address in search bar, it opens it in search engine. Is it possible to open it directly in browser? Fir example: I type "example.com", tap "search" and browser opens "example.com", not google/yandex/other engine page with search results for "example.com".

**Comment by zobnin** [comment]
There are two approaches to opening a website through search (and they are both applied in different browsers):

1. Try to figure out if the person wants to open a website rather than just searching for something. It seems simple—just check if the person entered a single word and it contains a dot—it's definitely a website. But no, I could be searching for `cmd.com`, which is both a website and an executable file name. Or I could be searching for a company called Cove.tool, and the system might try to open such a site (which doesn't exist). The problem is exacerbated by the fact that domain zones are now multiplying like mushrooms, and you can no longer just maintain a database of domain zones (.com, .org, .ru); it constantly changes.

2. The second approach is to treat anything as a search string and simply open the search results page. If it's a site and it exists, it will most likely appear at the top of the list, and the user just needs to click on the link.

I support the second approach.

**Comment by mj-sson** [comment]
It is now also possible to open websites directly from AIO Search 😀

![iMarkup_20241115_032730.png](https://github.com/user-attachments/assets/850a3125-7abe-4506-bc10-5c56dbba94dc)
