### ISSUE TITLE
No Web Results when using Startpage as a search provider

### ISSUE THREAD

**Issue by antdking** [zobnin/aio#17]
**Describe the bug**
Pretty much on the tin. No Web results when using Startpage, only on-device results. With + without VPN. 
DuckDuckGo results work fine.

**To Reproduce**
1. Set Startpage as your search provider
2. Go to 'Home'
3. Click on 'search' 
4. Type a search term (Hello World) 
5. No results

**Expected behavior**
Either:
- search results for StartPage
- or; a message to say Quick Results aren't supported for StartPage

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: pixel 6
 - Android version: 12 QRP
 - AIO Version: 4.4.0 beta 29

**Additional context**
I understand if this a feature to be implemented. 
I've raised as a bug instead; as, to a user, this is unexpected without messaging to explain it's not supported well, like what you do for under-screen fingerprints.

**Comment by zobnin** [comment]
Hm... StartPage removed its suggestions API so I will remove its support in the next version

**Comment by antdking** [comment]
Oh no, please don't drop support. Perhaps allow us to set our own search url, basic substitution?
It's useful to be able to type before opening the full browser (better app + Web being together)

**Comment by zobnin** [comment]
Yes, I will make it possible to add any search engine manually. No worries.

**Comment by zobnin** [comment]
AIO Launcher 4.4.0-beta13 now supports the connection of any search engine. To do this, you need to specify the address of the search query in the "Own search engine" option, replacing the search string with `%s`. For example:

```
https://google.com/search?q=%s
https://www.qwant.com/?q=%s
https://www.startpage.com/do/search?q=%s
https://engine.presearch.org/search?q=%s
```

**Comment by zobnin** [comment]
I don't see the point of bringing back support for a search engine that changes its API without warning, without maintaining backward compatibility. It would cost me more.

**Comment by zobnin** [comment]
You can write a simple search script that will handle search suggestions. Probably, a little later I will show an example of such a script for startpage.

**Comment by zobnin** [comment]
https://github.com/zobnin/aiolauncher_scripts/blob/master/community/starpage-search.lua

**Comment by mjdjohansson** [comment]
I stumbled across these messages after randomly installing the startpage script from the AIO Store. They appear every time you type a letter in search. Since I don't use startpage myself, I don't really know what they mean, but I thought I'd report it in case it's something important. Otherwise, please ignore this comment.

![Screenshot_20230930-135933.png](https://github.com/zobnin/aio/assets/121413314/22ad277d-0851-4ee7-8d40-e85bba0f8a9d)

![Screenshot_20230930-222302.png](https://github.com/zobnin/aio/assets/121413314/63aea5ba-c2b8-45d5-b9d4-e686a736fdea)

![Screenshot_20230930-222339.png](https://github.com/zobnin/aio/assets/121413314/5f1a7832-e85d-4bce-a747-62f59e78f558)

![Screenshot_20230930-222231.png](https://github.com/zobnin/aio/assets/121413314/f3bebc16-526e-47c3-ad6f-d174b700f6fb)

AIO Version: 4.9.1-beta4
Android: 13
Device: Google Pixel 7
