### ISSUE TITLE
The task widget needs a better date picker

### ISSUE THREAD

**Issue by penngrove** [zobnin/aio#22]
Editing the date components individually is not ideal, a calendar picker of sort would be great

My new favorite launcher...

**Comment by zobnin** [comment]
Did you know that the date buttons can be scrolled to the left or right?

**Comment by penngrove** [comment]
Yes, but I needed to pick a date next week and I needed to change month and day, clicking on a calendar would be a single click

**Comment by zobnin** [comment]
Yes, if the desired date is in the next month you need to change two fields. Just like with the standard dialog, you need to do two actions: first, open the dialog, and then click on the desired date (and therefore also close the dialog). But often the dates are in the same month and I think it's much easier to just scroll through one button.

In fact, I spent a lot of time to make the date selection in the current form. Because I don't consider jumping between different dialogs (in this case the note editing dialog and the date selection dialog) to be convenient. Also in the case of the standard date selection dialog, a separate time selection dialog would also be needed. That is, you would have to first open the date selection dialog, then close it and open the time selection dialog. That's just awful.

**Comment by penngrove** [comment]
A +1 day and -1 day button would be great then so I can hit it a few times
to get the correct date

**Comment by penngrove** [comment]
With rollover into the next or previous month

**Comment by zobnin** [comment]
You can add days, months and hours by long pressing task

**Comment by penngrove** [comment]
Nice, I did not see that, you can close this then, thank you
