### ISSUE TITLE
Google Clock app timer notification shows "Empty - Clock" 

### ISSUE THREAD

**Issue by dustinkerstein** [zobnin/aio#28]
When setting a timer in the Google Clock app, the notification in the pulldown Android Notification Drawer shows a live ticking timer countdown:
```
Clock
mm:ss
Timer
```
Whereas AIO's Notification widget shows "Empty - Clock" 

**To Reproduce**
1. install the Google Clock app
2. Set a timer
3. Note the discrepancy between the Notification Drawer and AIO Notification widget

**Expected behavior**
I'm not sure if AIO can support dynamic notifications like the timer countdown, but that would be ideal. If not, maybe an option to suppress these types of notifications would be a reasonable workaround. 

**Smartphone**
 - Device: Pixel XL
 - Android version: LineageOS 18.1
 - AIO Version: 4.5.1

![Screenshot_20220819-082811_Chrome](https://user-images.githubusercontent.com/7659306/185654146-e823f081-c1e4-4696-9f94-6757f1b3b9f8.png)
![Screenshot_20220819-082909_AIO_Launcher](https://user-images.githubusercontent.com/7659306/185654166-110eaa26-9361-4c57-9e4d-8fd3f1ea6705.png)

**Comment by zobnin** [comment]
Google Clock uses RemoteViews in its notification, in fact it is a widget that is built into the notification. The AIO Launcher does not show such notifications, because they would create mush in the interface. At the same time, I can't not show them because I have to give users the option to swipe such a notification. Maybe I should make an option to skip such notifications.

**Comment by dustinkerstein** [comment]
Thanks for the quick update. I'd vote for an option to skip these types of notifications. I think that's a very reasonable solution.
